const samsungData = [
  { "name": "Samsung Galaxy S (GT-I9000)", "architecture": "ARM Cortex-A8 (32-bit)" },
  { "name": "Samsung Galaxy S II (GT-I9100)", "architecture": "ARM Cortex-A9 (32-bit)" },
  { "name": "Samsung Galaxy S III (GT-I9300)", "architecture": "ARM Cortex-A9 (32-bit)" },
  { "name": "Samsung Galaxy S4 (GT-I9500)", "architecture": "ARM big.LITTLE (32-bit)" },
  { "name": "Samsung Galaxy S5 (SM-G900)", "architecture": "ARM big.LITTLE (32-bit)" },
  { "name": "Samsung Galaxy S6 (SM-G920)", "architecture": "ARM big.LITTLE (64-bit)" },
  { "name": "Samsung Galaxy S7 (SM-G930)", "architecture": "ARM big.LITTLE (64-bit)" },
  { "name": "Samsung Galaxy S8 (SM-G950)", "architecture": "ARM big.LITTLE (64-bit)" },
  { "name": "Samsung Galaxy S9 (SM-G960)", "architecture": "ARM big.LITTLE (64-bit)" },
  { "name": "Samsung Galaxy S10 (SM-G970)", "architecture": "ARM big.LITTLE (64-bit)" },
  { "name": "Samsung Galaxy S20 (SM-G980)", "architecture": "ARM big.LITTLE (64-bit)" },
  { "name": "Samsung Galaxy S21 (SM-G990)", "architecture": "ARM big.LITTLE (64-bit)" },
  { "name": "Samsung Galaxy S22 (SM-S900)", "architecture": "ARMv8.2-A (64-bit)" },
  { "name": "Samsung Galaxy S23 (SM-S910)", "architecture": "ARMv8.2-A (64-bit)" },
  { "name": "Samsung Galaxy S24 (SM-S921x)", "architecture": "ARMv8.2-A (64-bit)" },
  { "name": "Samsung Galaxy S24+ plus (SM-S926x)", "architecture": "ARMv8.2-A (64-bit)" },
  { "name": "Samsung Galaxy S24 Ultra (SM-S928x)", "architecture": "ARMv8.2-A (64-bit)" },
];
